---
title: "ساخت نمودار های سوال ۱"
output: html_document
---
# **توجه** این فایل صرفا ساخت نمودار ها می باشد و توضیحات در فایل بررسی **eda-final** آمده است.


### Importing libraries and setting paths
```{r}
base_folder <- "/home/amirsalar/Diabetes-R/" # change this:)

data_folder <- paste0(base_folder, "data/")
output_folder <- paste0(base_folder, "output/")

diabetes_012_path <- paste0(data_folder,"diabetes_012_health_indicators_BRFSS2015.csv")
diabetes_binary_5050_path <- paste0(data_folder, "diabetes_binary_5050split_health_indicators_BRFSS2015.csv")
diabetes_binary_path <- paste0(data_folder, "diabetes_binary_health_indicators_BRFSS2015.csv")

library(data.table)
library(ggplot2)
library(readxl)
library(corrplot)
```
### Loading datasets
```{r}
dt_012 <- data.table(read.csv(diabetes_012_path))
dt_5050 <- data.table(read.csv(diabetes_binary_5050_path))
dt <- data.table(read.csv(diabetes_binary_path))
```


### Lets See data and test hypothesises
```{r}
corr <- cor(dt_5050)
corrplot(corr, addCoef.col = 1)
```



```{r}
ggplot(dt_5050, aes(BMI, fill = Diabetes_binary))+
  geom_density(alpha = .70)+
  scale_fill_discrete(labels=c('No Diabetes', 'Has Diabetes'))

ggsave(filename = paste0(output_folder, "BMI-distribution.png"), width = 800, height = 600, units = "px", dpi = 100)
```
```{r}
ggplot(dt_5050, aes(GenHlth, fill = Diabetes_binary))+
  geom_bar(alpha = .75)+
  facet_wrap(Diabetes_binary ~ ., scales = 'free_y')+
  scale_fill_discrete(labels=c( 'No Diabetes', 'Diabetes'))

ggsave(filename = paste0(output_folder, "General-health-distribution.png"), width = 1000, height = 750, units = "px", dpi = 100)
```
```{r}
ggplot(dt_5050, aes(HighBP, fill = Diabetes_binary))+
  geom_bar( alpha = .75)+
  facet_wrap(Diabetes_binary ~ ., scales = 'free_y')+
  scale_fill_discrete(labels=c('No Diabetes', 'Diabetes'))

ggsave(filename = paste0(output_folder, "High-Blood-Pressure-distribution.png"), width = 1000, height = 750, units = "px", dpi = 100)
```
```{r}
ggplot(dt_5050, aes(Age, fill = Diabetes_binary))+
  geom_boxplot() +
  scale_fill_discrete(labels=c('No Diabetes', 'Diabetes'))
ggsave(filename = paste0(output_folder, "age-distribution.png"), width = 1000, height = 750, units = "px", dpi = 100)

```
